#!/bin/bash

# The intention is to have a script that can run with 
#    curl -s "https://raw.githubusercontent.com/openlibraryenvironment/platform-rs/master/helper_scripts/setup" | bash
# Which will configure a ux env

mkdir rs_ui
cd rs_ui

# Copy the workspace package.json
wget https://raw.githubusercontent.com/openlibraryenvironment/platform-rs/master/helper_scripts/package.json

git clone git@github.com:openlibraryenvironment/platform-rs.git
git clone git@github.com:openlibraryenvironment/ui-rs.git
git clone git@github.com:openlibraryenvironment/ui-directory.git
git clone git@github.com:openlibraryenvironment/ui-request.git
git clone git@github.com:openlibraryenvironment/ui-update.git
git clone git@github.com:openlibraryenvironment/ui-supply.git
git clone git@github.com:openlibraryenvironment/stripes-reshare.git

echo Completed clone and setup
echo cd rs_ui/platform-rs and run "yarn install" to download deps, then "stripes serve ./stripes.config.js --hasAllPerms" to start the UI
